"""empty message

Revision ID: 876fef8f0e61
Revises: 619177dd04a5
Create Date: 2022-02-15 15:16:01.087624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876fef8f0e61'
down_revision = '619177dd04a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_direct_channels',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direct_channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direct_channel_id'], ['direct_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_direct_channels')
    # ### end Alembic commands ###
