"""empty message

Revision ID: 6b6f79da197d
Revises: c10a87c8089e
Create Date: 2022-02-15 12:35:52.742166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6f79da197d'
down_revision = 'c10a87c8089e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_servers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name='association_server_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_user_id_fkey')
    )
    op.drop_table('users_servers')
    # ### end Alembic commands ###
