"""empty message

Revision ID: 61458ca286c6
Revises: 876fef8f0e61
Create Date: 2022-02-15 15:29:15.229687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61458ca286c6'
down_revision = '876fef8f0e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direct_channel_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['direct_channel_id'], ['direct_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_messages')
    # ### end Alembic commands ###
